[workspace]
members = ["smart_tray"]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["SI"]
edition = "2021"
rust-version = "1.78"

license-file = "LICENSE"

[workspace.dependencies]
tauri = "1.6"
tauri-build = { version = "1.5", features = [] }
log = "0.4"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
chrono = "0.4"
once_cell = { version = "1.19"}

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
strip = "symbols"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
dbg_macro = "deny"
todo = "deny"