[workspace]
members = ["smart_tray", "controller", "idler_utils"]   
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["ah"]
edition = "2021"

[workspace.dependencies]
tauri = { version = "1.5.4" }
tauri-build = { version = "1.5.1", features = [] }
log = "0.4.20"
env_logger = "0.11.2"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true 